sonar.projectKey=lp-comunidade
sonar.projectName=InnovaNation - Landing Comunidade
sonar.sources=app,lib,scripts,middleware.ts,next.config.ts
sonar.exclusions=**/node_modules/**,**/.next/**,public/**,**/*.d.ts
sonar.sourceEncoding=UTF-8
sonar.javascript.node.debugMemory=true
