sonar.projectKey=lp-comunidade
sonar.projectName=InnovaNation - Landing Comunidade
sonar.sources=app,lib,scripts
sonar.exclusions=**/node_modules/**,**/.next/**,public/**,**/*.d.ts
sonar.sourceEncoding=UTF-8
