import { isValidCNPJ, onlyDigits } from './br-documents';
import type {
  EditalDraftRequestDto,
  EditalDraftStep,
  EditalValidationDto,
} from './edital-client-types';
import {
  EDITAL_MAX_BUDGET_DESCRIPTION_LENGTH,
  EDITAL_MAX_BUDGET_ITEMS,
  EDITAL_MAX_BUDGET_ITEM_VALUE,
  EDITAL_MAX_BUDGET_JUSTIFICATION_LENGTH,
  EDITAL_MAX_TEXT_LENGTH,
  isAutoGeneratedDocumentCode,
  isEditalDocumentRequirementCode,
} from './edital-requirements';

type ParseResult<T> = { ok: true; value: T } | { ok: false; error: EditalValidationDto };

type UploadFields = {
  requirementCode?: unknown;
  file?: unknown;
};

const VALID_STEPS = new Set<EditalDraftStep>(['equipe', 'instituicao', 'fotos', 'proposta']);
const OUTER_DRAFT_FIELDS = new Set(['step', 'data']);
const UPLOAD_FIELDS = new Set(['requirementCode', 'file']);

const STEP_FIELDS: Record<EditalDraftStep, readonly string[]> = {
  equipe: ['team_description'],
  instituicao: [
    'institution_name',
    'institution_cnpj',
    'lab_name',
    'lab_area',
    'lab_served_public',
    'lab_academic_unit',
  ],
  fotos: ['lab_structure_description'],
  proposta: ['budget_items', 'technical_justification', 'expected_results', 'main_improvement_objective'],
};

function validationError(message = 'Payload inválido'): ParseResult<never> {
  return {
    ok: false,
    error: {
      error: 'validation_error',
      message,
    },
  };
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return Boolean(value) && typeof value === 'object' && !Array.isArray(value);
}

function isFormData(value: unknown): value is FormData {
  return typeof FormData !== 'undefined' && value instanceof FormData;
}

function hasOnlyKeys(value: Record<string, unknown>, allowed: Set<string> | readonly string[]): boolean {
  const allowedSet = allowed instanceof Set ? allowed : new Set(allowed);
  return Object.keys(value).every((key) => allowedSet.has(key));
}

function formDataToUploadFields(input: FormData): UploadFields | null {
  const entries = Array.from(input.entries());
  if (entries.length !== UPLOAD_FIELDS.size || entries.some(([key]) => !UPLOAD_FIELDS.has(key))) {
    return null;
  }

  return {
    requirementCode: input.get('requirementCode'),
    file: input.get('file'),
  };
}

function containsDangerousInput(value: string): boolean {
  return /<\s*script|<\s*iframe|<\s*svg|javascript:|data:text\/html|vbscript:|onerror\s*=|onload\s*=|onclick\s*=/i.test(value);
}

function normalizeText(value: unknown): string | null {
  if (value === null || value === undefined) {
    return null;
  }
  if (typeof value !== 'string') {
    throw new Error('Payload inválido');
  }
  if (value.length > EDITAL_MAX_TEXT_LENGTH || containsDangerousInput(value)) {
    throw new Error('Payload inválido');
  }

  const trimmed = value.trim();
  return trimmed.length > 0 ? trimmed : null;
}

function normalizeCnpj(value: unknown): string | null {
  const text = normalizeText(value);
  if (!text) {
    return null;
  }

  const digits = onlyDigits(text);
  if (digits.length === 0) {
    return null;
  }
  if (digits.length === 14 && !isValidCNPJ(digits)) {
    throw new Error('Payload inválido');
  }

  return digits;
}

function normalizeBudgetItems(value: unknown) {
  if (value === null || value === undefined) {
    return null;
  }
  if (!Array.isArray(value) || value.length > EDITAL_MAX_BUDGET_ITEMS) {
    throw new Error('Payload inválido');
  }

  return value.map((item) => {
    if (!isRecord(item) || !hasOnlyKeys(item, ['descricao', 'valor_estimado', 'justificativa'])) {
      throw new Error('Payload inválido');
    }

    const descricao = normalizeText(item.descricao) ?? '';
    const justificativa = normalizeText(item.justificativa) ?? '';
    const valorEstimado = item.valor_estimado;

    if (
      descricao.length === 0 ||
      descricao.length > EDITAL_MAX_BUDGET_DESCRIPTION_LENGTH ||
      justificativa.length === 0 ||
      justificativa.length > EDITAL_MAX_BUDGET_JUSTIFICATION_LENGTH ||
      typeof valorEstimado !== 'number' ||
      !Number.isFinite(valorEstimado) ||
      valorEstimado <= 0 ||
      valorEstimado > EDITAL_MAX_BUDGET_ITEM_VALUE
    ) {
      throw new Error('Payload inválido');
    }

    return {
      descricao,
      valor_estimado: valorEstimado,
      justificativa,
    };
  });
}

export function parseDraftRequest(input: unknown): ParseResult<EditalDraftRequestDto> {
  try {
    if (!isRecord(input) || !hasOnlyKeys(input, OUTER_DRAFT_FIELDS)) {
      return validationError();
    }

    const step = typeof input.step === 'string' && VALID_STEPS.has(input.step as EditalDraftStep)
      ? (input.step as EditalDraftStep)
      : null;
    if (!step) {
      return validationError();
    }

    const data = input.data === undefined ? {} : input.data;
    if (!isRecord(data) || !hasOnlyKeys(data, STEP_FIELDS[step])) {
      return validationError();
    }

    if (step === 'equipe') {
      return { ok: true, value: { step, data: { team_description: normalizeText(data.team_description) } } };
    }
    if (step === 'instituicao') {
      return {
        ok: true,
        value: {
          step,
          data: {
            institution_name: normalizeText(data.institution_name),
            institution_cnpj: normalizeCnpj(data.institution_cnpj),
            lab_name: normalizeText(data.lab_name),
            lab_area: normalizeText(data.lab_area),
            lab_served_public: normalizeText(data.lab_served_public),
            lab_academic_unit: normalizeText(data.lab_academic_unit),
          },
        },
      };
    }
    if (step === 'fotos') {
      return {
        ok: true,
        value: { step, data: { lab_structure_description: normalizeText(data.lab_structure_description) } },
      };
    }

    return {
      ok: true,
      value: {
        step,
        data: {
          budget_items: normalizeBudgetItems(data.budget_items),
          technical_justification: normalizeText(data.technical_justification),
          expected_results: normalizeText(data.expected_results),
          main_improvement_objective: normalizeText(data.main_improvement_objective),
        },
      },
    };
  } catch {
    return validationError();
  }
}

export function parseDocumentUploadFields(input: unknown): ParseResult<{ requirementCode: string; file: unknown }> {
  const fields = isFormData(input)
    ? formDataToUploadFields(input)
    : isRecord(input) && hasOnlyKeys(input, UPLOAD_FIELDS)
      ? input
      : null;

  if (!fields) {
    return validationError();
  }
  if (
    typeof fields.requirementCode !== 'string' ||
    !isEditalDocumentRequirementCode(fields.requirementCode) ||
    isAutoGeneratedDocumentCode(fields.requirementCode)
  ) {
    return validationError();
  }
  if (fields.file === undefined || fields.file === null) {
    return validationError();
  }

  return {
    ok: true,
    value: {
      requirementCode: fields.requirementCode,
      file: fields.file,
    },
  };
}

export function toStableErrorDto(
  error: unknown,
  options: { error?: string; fallbackMessage?: string; missing?: EditalValidationDto['missing'] } = {}
): EditalValidationDto {
  void error;

  return {
    error: options.error ?? 'validation_error',
    ...(options.fallbackMessage ? { message: options.fallbackMessage } : {}),
    ...(options.missing ? { missing: options.missing } : {}),
  };
}
